name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
          DEBUG: "True"  # Enable debugging

      # Remove the "🐱 My GitHub Data" line from the README
      - name: Remove "🐱 My GitHub Data" heading
        run: |
          sed -i '/🐱 My GitHub Data/d' README.md
          
      # Commit the changes back to the repo
      - name: Commit changes to README
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update README with WakaTime stats'
          add: 'README.md'
